---
- import_tasks: populate/update_all_cluster_variables.yaml
- import_tasks: populate/update_k8s_cluster_kube_apiserver_ip.yaml
- import_tasks: populate/update_k8s_cluster_variables.yaml
- import_tasks: populate/update_k8s_addons_variables.yaml
- import_tasks: populate/update_all_docker.yaml
- import_tasks: populate/update_all_containerd.yaml
- import_tasks: populate/update_etcd.yaml
